version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - webnet
    image: jazevedo6/cinema-system-db
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:5000"
    env_file: ./.env
    networks:
      - webnet
    image: jazevedo6/cinema-system-api
networks:
  webnet:
