version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: Team20
    ports:
      - "5432:5432"
    networks:
      - webnet
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:5000"
    env_file: ./.env
    networks:
      - webnet
networks:
  webnet:
